[grpc]
address = "0.0.0.0:50051"

[database]
url = "ws://surrealdb:8000"
namespace = "scylla"
database = "core"
username = "root"
password = "root"

[cors]
allow_origins = ["http://localhost:5173", "http://localhost:8080"]
allow_headers = [
    "content-type",
    "authorization",
    "x-grpc-web",
    "x-user-agent"
]
expose_headers = [
    "grpc-status",
    "grpc-message",
    "grpc-status-details-bin"
]

[broker]
url = "http://scylla-broker:50052"

[bootstrap]
username = "admin"
password = "admin123"
