[grpc]
address = "127.0.0.1:50051"

[database]
url = "ws://127.0.0.1:8000"
namespace = "scylla"
database = "core"
username = "root"
password = "root"

[cors]
allow_origins = ["*"]
allow_headers = [
    "content-type",
    "authorization",
    "x-grpc-web",
    "x-user-agent"
]
expose_headers = [
    "grpc-status",
    "grpc-message",
    "grpc-status-details-bin"
]

[broker]
url = "http://127.0.0.1:50052"

[bootstrap]
username = "admin"
password = "admin123"
