[package]
name = "scylla-broker"
version = "0.1.0"
edition = "2024"

[dependencies]
hermes-broker-core = { workspace = true }
hermes-broker-proto = { workspace = true }
hermes-broker-server = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tonic-reflection = { workspace = true }
