[package]
name = "scylla-broker"
version = "0.1.0"
edition = "2024"

[dependencies]
hermes-broker-server = "0.3"
hermes-broker-store = "0.3"
hermes-broker-proto = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.18", features = [] }
tonic = "0.14.5"
tracing = "0.1"
tracing-subscriber = "0.3"
tonic-reflection = "0.14.5"
