[package]
name = "scylla-broker"
version = "0.1.0"
edition = "2024"

[dependencies]
hermes-broker-core = { workspace = true }
hermes-broker-proto = { workspace = true }
hermes-broker-server = { workspace = true }
tokio = { version = "1", features = ["full"] }
tonic = "0.14.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tonic-reflection = "0.14.5"
