[request_definition]
r = sub, scope, resource, act

[policy_definition]
p = sub, scope, resource, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.scope) \
    && keyMatch(r.scope, p.scope) \
    && keyMatch(r.resource, p.resource) \
    && keyMatch(r.act, p.act)