services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scylla
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - reverse-proxy
      - back-end
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 12

  core:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: scylla-core
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 50051
    environment:
      RUST_LOG: debug
    command: [ "--config", "/app/config/docker.toml" ]
    volumes:
      - ./apps/server/config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scylla-grpc.rule=Host(`dev.scylla-ops.com`) && PathPrefix(`/api`)"

      - "traefik.http.routers.scylla-grpc.entrypoints=websecure"
      - "traefik.http.routers.scylla-grpc.tls.certresolver=myresolver"

      - "traefik.http.services.scylla-grpc.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.scylla-grpc.loadbalancer.server.port=50051"
      - "traefik.http.middlewares.scylla-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.scylla-grpc-web.grpcWeb.allowOrigins=*"
      - "traefik.http.routers.scylla-grpc.middlewares=scylla-stripprefix,scylla-grpc-web"

    networks:
      - reverse-proxy
      - back-end

networks:
  reverse-proxy:
    external: true
  back-end:

volumes:
  db_data:
