services:
  core:
    build:
      context: .
      dockerfile: apps/core/Dockerfile
    container_name: scylla-core
    ports:
      - "50051:50051"
    environment:
      RUST_LOG: debug
    command: ["--config", "/app/config/docker.toml"]
    volumes:
      - ./apps/core/config:/app/config
      - core_data:/data
