services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scylla
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 12

  core:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: scylla-core
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"   # gRPC
    environment:
      RUST_LOG: info
    command: [ "--config", "/app/config/docker.toml" ]
    volumes:
      - ./apps/server/config:/app/config


volumes:
  db_data: