# Docker configuration for Scylla Core

[core_config]
grpc_config = "0.0.0.0:50051"

[core_config.database_config]
url = "ws://db:8000"
username = "root"
password = "secret"
namespace = "app"
database = "main"