[grpc]
address = "0.0.0.0:50051"

[database]
url = "ws://db:8000"
username = "root"
password = "secret"
namespace = "scylla"
database = "core"

[cors]
allow_origins = ["*"]

[bootstrap]
username = "admin"
password = "admin123"
