[package]
name = "interfaces"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
tonic = { version = "0.14.2", features = ["server"] }
log = "0.4.28"
derive_more = { version = "2.1.1", features = ["constructor"] }
async-trait = "0.1.89"
toml = "0.9.8"

[build-dependencies]
tonic-prost-build = "0.14.2"
