[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[features]
surrealdb = ["dep:surrealdb-types", "dep:surrealdb"]

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
derive_more.workspace = true
chrono.workspace = true
ulid.workspace = true
surrealdb = { workspace = true, optional = true }
surrealdb-types = { workspace = true, optional = true }
