[package]
name = "scylla-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
protocol = { path = "../../libs/protocol"}
tracing = "0.1.41"
async-trait = "0.1.89"
anyhow = { version = "1.0.81" }
serde = { version = "1.0.225", features = ["derive"] }
clap = { version = "4.5.4", features = ["derive"] }
derive_builder = { version = "0.20.2", features = ["default"] }
derive_more = { version = "2.0.1", features = ["full"] }
tokio-stream = "0.1.17"
