[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "./domain", features = ["surrealdb"] }
application = { path = "./application" }
infrastructure = { path = "./infrastructure" }
interfaces = { path = "./interfaces" }
protocol.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-reflection.workspace = true
surrealdb.workspace = true
serde.workspace = true
toml.workspace = true
clap.workspace = true
anyhow.workspace = true
tower-http.workspace = true
http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
